export const defaultLayoutConfig = {
  mediaFrame: {
    leftPct: 23.9,
    topPct: 17.1,
    widthPct: 53.8,
    heightPct: 57.6,
    borderRadiusRem: 0.2,
  },
  textBlock: {
    leftPct: 19.6,
    topPct: 74.2,
    widthPct: 59.9,
    heightPct: 10.8,
    fontSizeRem: 1.4,
    lineHeight: 1.28,
    textAlign: "center",
  },
  pageCounter: {
    leftPct: 42.5,
    topPct: 88.6,
    widthPct: 12.6,
    fontSizeRem: 0.98,
    textAlign: "center",
  },
  skipButton: {
    leftPct: 1.5,
    bottomPct: 16.0,
    minHeightRem: 3.5,
    paddingInlineRem: 1.0,
    fontSizeRem: 1.02,
    iconSizeRem: 2.2,
  },
  muteButton: {
    leftPct: 5.0,
    topPct: 5.2,
    minHeightRem: 3.15,
    paddingInlineRem: 1.0,
    fontSizeRem: 0.98,
  },
  prevButton: {
    leftPct: 23.1,
    bottomPct: 8.0,
    minWidthRem: 8.6,
    minHeightRem: 3.0,
    fontSizeRem: 1.12,
  },
  forwardButton: {
    leftPct: 67.6,
    bottomPct: 8.0,
    minWidthRem: 9.0,
    minHeightRem: 3.0,
    fontSizeRem: 1.12,
  },
};

export const layoutControlSchema = [
  {
    section: "视频区域",
    controls: [
      { path: "mediaFrame.leftPct", label: "left %", min: 0, max: 100, step: 0.1, unit: "%" },
      { path: "mediaFrame.topPct", label: "top %", min: 0, max: 100, step: 0.1, unit: "%" },
      { path: "mediaFrame.widthPct", label: "width %", min: 1, max: 100, step: 0.1, unit: "%" },
      { path: "mediaFrame.heightPct", label: "height %", min: 1, max: 100, step: 0.1, unit: "%" },
      {
        path: "mediaFrame.borderRadiusRem",
        label: "圆角 rem",
        min: 0,
        max: 4,
        step: 0.05,
        unit: "rem",
      },
    ],
  },
  {
    section: "文字区域",
    controls: [
      { path: "textBlock.leftPct", label: "left %", min: 0, max: 100, step: 0.1, unit: "%" },
      { path: "textBlock.topPct", label: "top %", min: 0, max: 100, step: 0.1, unit: "%" },
      { path: "textBlock.widthPct", label: "width %", min: 1, max: 100, step: 0.1, unit: "%" },
      { path: "textBlock.heightPct", label: "height %", min: 1, max: 50, step: 0.1, unit: "%" },
      {
        path: "textBlock.fontSizeRem",
        label: "字号 rem",
        min: 0.6,
        max: 3.2,
        step: 0.02,
        unit: "rem",
      },
      {
        path: "textBlock.lineHeight",
        label: "行高",
        min: 0.8,
        max: 2.5,
        step: 0.01,
        unit: "",
      },
      {
        path: "textBlock.textAlign",
        label: "对齐",
        type: "select",
        options: [
          { value: "left", label: "左对齐" },
          { value: "center", label: "居中" },
          { value: "right", label: "右对齐" },
        ],
      },
    ],
  },
  {
    section: "页码",
    controls: [
      { path: "pageCounter.leftPct", label: "left %", min: 0, max: 100, step: 0.1, unit: "%" },
      { path: "pageCounter.topPct", label: "top %", min: 0, max: 100, step: 0.1, unit: "%" },
      {
        path: "pageCounter.widthPct",
        label: "width %",
        min: 1,
        max: 40,
        step: 0.1,
        unit: "%",
      },
      {
        path: "pageCounter.fontSizeRem",
        label: "字号 rem",
        min: 0.5,
        max: 2.4,
        step: 0.02,
        unit: "rem",
      },
      {
        path: "pageCounter.textAlign",
        label: "对齐",
        type: "select",
        options: [
          { value: "left", label: "左对齐" },
          { value: "center", label: "居中" },
          { value: "right", label: "右对齐" },
        ],
      },
    ],
  },
  {
    section: "跳过按钮",
    controls: [
      { path: "skipButton.leftPct", label: "left %", min: 0, max: 40, step: 0.1, unit: "%" },
      {
        path: "skipButton.bottomPct",
        label: "bottom %",
        min: 0,
        max: 40,
        step: 0.1,
        unit: "%",
      },
      {
        path: "skipButton.minHeightRem",
        label: "高度 rem",
        min: 2,
        max: 6,
        step: 0.05,
        unit: "rem",
      },
      {
        path: "skipButton.paddingInlineRem",
        label: "内边距 rem",
        min: 0.2,
        max: 2.5,
        step: 0.05,
        unit: "rem",
      },
      {
        path: "skipButton.fontSizeRem",
        label: "字号 rem",
        min: 0.7,
        max: 2,
        step: 0.02,
        unit: "rem",
      },
      {
        path: "skipButton.iconSizeRem",
        label: "图标 rem",
        min: 1,
        max: 4,
        step: 0.05,
        unit: "rem",
      },
    ],
  },
  {
    section: "静音按钮",
    controls: [
      { path: "muteButton.leftPct", label: "left %", min: 0, max: 40, step: 0.1, unit: "%" },
      { path: "muteButton.topPct", label: "top %", min: 0, max: 40, step: 0.1, unit: "%" },
      {
        path: "muteButton.minHeightRem",
        label: "高度 rem",
        min: 2,
        max: 6,
        step: 0.05,
        unit: "rem",
      },
      {
        path: "muteButton.paddingInlineRem",
        label: "内边距 rem",
        min: 0.2,
        max: 2.5,
        step: 0.05,
        unit: "rem",
      },
      {
        path: "muteButton.fontSizeRem",
        label: "字号 rem",
        min: 0.7,
        max: 2,
        step: 0.02,
        unit: "rem",
      },
    ],
  },
  {
    section: "上一页按钮",
    controls: [
      { path: "prevButton.leftPct", label: "left %", min: 0, max: 100, step: 0.1, unit: "%" },
      { path: "prevButton.bottomPct", label: "bottom %", min: 0, max: 30, step: 0.1, unit: "%" },
      {
        path: "prevButton.minWidthRem",
        label: "宽度 rem",
        min: 4,
        max: 16,
        step: 0.05,
        unit: "rem",
      },
      {
        path: "prevButton.minHeightRem",
        label: "高度 rem",
        min: 2,
        max: 6,
        step: 0.05,
        unit: "rem",
      },
      {
        path: "prevButton.fontSizeRem",
        label: "字号 rem",
        min: 0.7,
        max: 2,
        step: 0.02,
        unit: "rem",
      },
    ],
  },
  {
    section: "下一页 / 进入游戏按钮",
    controls: [
      { path: "forwardButton.leftPct", label: "left %", min: 0, max: 100, step: 0.1, unit: "%" },
      {
        path: "forwardButton.bottomPct",
        label: "bottom %",
        min: 0,
        max: 30,
        step: 0.1,
        unit: "%",
      },
      {
        path: "forwardButton.minWidthRem",
        label: "宽度 rem",
        min: 4,
        max: 18,
        step: 0.05,
        unit: "rem",
      },
      {
        path: "forwardButton.minHeightRem",
        label: "高度 rem",
        min: 2,
        max: 6,
        step: 0.05,
        unit: "rem",
      },
      {
        path: "forwardButton.fontSizeRem",
        label: "字号 rem",
        min: 0.7,
        max: 2,
        step: 0.02,
        unit: "rem",
      },
    ],
  },
];
